### ISSUE TITLE
Separate model from operations on it

### ISSUE THREAD

**Issue by qwazer** [bsorrentino/maven-confluence-plugin#170]
I want to share a couple of thoughts about the plugin.

Internal model structure and API is hard to understand. It makes difficult to contribute and evolve the plugin.

I suggest to separate model implemented in class org.bsc.confluence.model.Site,

* remove any methods like org.bsc.confluence.model.Site#processUriContent from model classes (model classes should have an only getter, setter, and constructors)
* make model part of public API (it is public API indeed, but some classes marked as protected: `protected static class Source`)
* use the same model in the feature "avoid page republishing". Currently, the new model description in JSON format was added. The feature "avoid page republishing" can be implemented without adding a new model in several ways like
   * adding `contentSourceHash` field to `Source` object - what is proposed in #167 
   * adding `contentConvertedHash` after implementing more robust solution proposed in #163
New fields above is not part of input site.yaml, it if fields for internal  `confluence-reporting-maven-plugin-storage.yaml`

* The model can be extended in future to support more use cases, like page renames both on client-side and server-side
  *  Rename page on client side:
     *  analyzing field `name` to method  `isUpdated` 
     * adding field 'counfluencePageId' to track server-side renames (inroduce method `isMoved` or `needToMove`)

* To support feature  "avoid page republishing" model should include ConfluenceSiteDescription - enpointURL + SpaceKey.
    
Just for reference, model example (from 716fec5ffc658e2c9702f3b80194043434d7ec96 ). Possibly should be extended by fields above.
```yaml
#site:
home:
  uri: encoding.confluence
  children:
    - name: "page 1"
      uri: page1.md    
    - name: "page 2"
      uri: page2.md    
      attachments:
        - name: "attach1.png" 
          uri: attach1.png
          comment: attach1_comment 
          contentType: "image/png" 
          version: 1  
  attachments:
    - name: "home.png" 
      uri: home.png
      comment: home_comment 
      contentType: "image/png" 
      version: 1  
labels:    
  - encoding
  - test      
        
```
