### ISSUE TITLE
use the site model in the feature "avoid page republishing"

### ISSUE THREAD

**Issue by bsorrentino** [bsorrentino/maven-confluence-plugin#171]
This issue has been splitted by #170 proposed by @qwazer
* use the same model in the feature "avoid page republishing". Currently, the new model description in JSON format was added. The feature "avoid page republishing" can be implemented without adding a new model in several ways like
   * adding `contentSourceHash` field to `Source` object - refered to #167 
   * adding `contentConvertedHash` after implementing more robust solution proposed in #163
New fields above is not part of input site.yaml, it if fields for internal  `confluence-reporting-maven-plugin-storage.yaml`

* The model can be extended in future to support more use cases, like page renames both on client-side and server-side
  *  Rename page on client side:
     *  analyzing field `name` to method  `isUpdated` 
     * adding field 'counfluencePageId' to track server-side renames (inroduce method `isMoved` or `needToMove`)

* To support feature  "avoid page republishing" model should include ConfluenceSiteDescription - enpointURL + SpaceKey.
    
Just for reference, model example (from 716fec5ffc658e2c9702f3b80194043434d7ec96 ). Possibly should be extended by fields above.
```yaml
#site:
home:
  uri: encoding.confluence
  children:
    - name: "page 1"
      uri: page1.md    
    - name: "page 2"
      uri: page2.md    
      attachments:
        - name: "attach1.png" 
          uri: attach1.png
          comment: attach1_comment 
          contentType: "image/png" 
          version: 1  
  attachments:
    - name: "home.png" 
      uri: home.png
      comment: home_comment 
      contentType: "image/png" 
      version: 1  
labels:    
  - encoding
  - test      
        
```
