### ISSUE TITLE
relative link breaks deployment on Confluence Cloud

### ISSUE THREAD

**Issue by petargadjev** [bsorrentino/maven-confluence-plugin#227]
Hello,

When using Markdown relative links to files within the root of the project (e.g. `* [Help](HELP.md)`) the `deploy` action throws an exception with message:

```
org.bsc.confluence.rest.AbstractRESTConfluenceService$ServiceException: error: update page
Response{protocol=h2, code=400, message=, url=https://aiopsgroup.atlassian.net/wiki/rest/api/content/744751135}
{"statusCode":400,"data":{"authorized":false,"valid":true,"errors":[],"successful":false},"message":"com.atlassian.confluence.api.service.exceptions.BadRequestException: Content body cannot be converted to new editor format"}
```

There is a bug logged on the CONFCLOUD board which seams like a match: https://jira.atlassian.com/browse/CONFCLOUD-69902

I am testing against Confluence Cloud and it throws exception for any type of file being used in the link - md, json, txt.
Tested with:

- version `6.8` with `Java 13` + `confluence-markdown-processor-commonmark`
- version `6.9` with `Java 8` + `confluence-markdown-processor-commonmark`

My `pom.xml` is
```
	<build>
		<plugins>
			<plugin>
				<groupId>org.bsc.maven</groupId>
				<artifactId>confluence-reporting-maven-plugin</artifactId>
				<version>6.8</version>
				<dependencies>
					<dependency>
						<groupId>org.bsc.maven</groupId>
						<artifactId>confluence-markdown-processor-commonmark</artifactId>
						<version>6.8</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
				<configuration>
					<spaceKey>MYSPACE</spaceKey>
					<siteDescriptor>${basedir}/src/site/confluence/site.yaml</siteDescriptor>
					<markdownProcessor>
						<name>commonmark</name>
					</markdownProcessor>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

`site.yaml` is
```
home:
  uri: README.md
  parentPageTitle: "All my projects"
  name: "Demo project"
  attachments:
    - name: "process.png"
      uri: images
      comment: image
      contentType: "image/png"
      version: 1
    - name: "payload.json"
      uri: examples
      comment: payload
      contentType: "application/json"
      version: 1
  children:
    - name: "How to get help"
      uri: help/HELP.md
```

`README.md` is
```
* [Help](HELP.md)
```

I could provide full stacktrace once requested.

Thank you very much for the hard work, really amazing plugin.

* EDIT: there were two typos in the last sentence
